#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.9.2d12 - util/clean_nu_codebase - LICENSE: PUB_DOM
#
# Written in 2013 Chad Jacob Milios and Crop Circle Systems, Inc.
# All rights reserved.
#
# This Source Code Form is placed in the public domain by the author, who disclaims all
# liability. More information can be found in the license file.
#
# Official updates and community support available at http://nuos.org .
# Other licensing options and professional services available at http://ccsys.com .

NUOS_VER=0.0.9.2d12
NUOS_CODE_ROOT="$(realpath "$(dirname "$(realpath "$0")")/../")"

[ "$NUOS_CODE_ROOT" != /usr/nuos -a "$NUOS_CODE_ROOT" != /usr -a "$NUOS_CODE_ROOT" != / ]

find . -name '.*' -not -name . -print0 | xargs -0 rm -rf
