#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.11.4a0 - util/dump_zfs_layout
#
# Copyright (c) 2008-2020 Chad Jacob Milios and Crop Circle Systems.
# All rights reserved.
#
# This Source Code Form is subject to the terms of the Simplified BSD License.
# If a copy of the Simplified BSD License was not distributed alongside this file, you can
# obtain one at https://www.freebsd.org/copyright/freebsd-license.html . This software
# project is not affiliated with the FreeBSD Project.
#
# Official updates and community support available at https://nuos.org .
# Professional services available at https://ccsys.com .

NUOS_VER=0.0.11.4a0

. "$(dirname "$(realpath "$0")")/../lib/nu_system.sh"
. "$(dirname "$(realpath "$0")")/../lib/nu_common.sh"

from_ds=${1-}

nuos_init -q

: ${from_ds:=$POOL_BOOT_NAME}

{
	for ds in `zfs list -r -H -p -o name $from_ds`; do
		zfs get -H -p all $ds
	done
} | grep -E -v '	(used|available|logicalused|usedbydataset|usedbysnapshots|compressratio|refcompressratio|usedbychildren|referenced|logicalreferenced|written|creation)	'
