#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.11.0b0.1 - util/mnt - LICENSE: PUB_DOM
#
# Written in 2013 Chad Jacob Milios and Crop Circle Systems, Inc.
# All rights reserved.
#
# This Source Code Form is placed in the public domain by the author, who disclaims all
# liability. More information can be found in the license file.
#
# Official updates and community support available at https://nuos.org .
# Other licensing options and professional services available at https://ccsys.com .

NUOS_VER=0.0.11.0b0.1

mount | sed -E -e 's/^(.*) on (.*) \((.*)\)$/\1	\2	\3/'
