#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.11.3a0 - util/nu_version
#
# Copyright (c) 2008-2019 Chad Jacob Milios and Crop Circle Systems.
# All rights reserved.
#
# This Source Code Form is subject to the terms of the Simplified BSD License.
# If a copy of the Simplified BSD License was not distributed alongside this file, you can
# obtain one at https://www.freebsd.org/copyright/freebsd-license.html . This software
# project is not affiliated with the FreeBSD Project.
#
# Official updates and community support available at https://nuos.org .
# Professional services available at https://ccsys.com .

NUOS_VER=0.0.11.3a0

NUOS_CODE_ROOT="$(realpath "$(dirname "$(realpath "$0")")/../")"

[ "$NUOS_CODE_ROOT" != /usr/nuos -a "$NUOS_CODE_ROOT" != /usr -a "$NUOS_CODE_ROOT" != / ]

if [ -n "${1-}" ]; then
	new_ver=$1
else
	new_ver=`basename "$NUOS_CODE_ROOT"`
	[ $new_ver != nuOS -a $new_ver != nuos ]
fi

cd "$NUOS_CODE_ROOT"
export LC_CTYPE=C

readmes="`find -E . -type f -depth 1 -regex './[[:upper:]]+'`"
libs="lib/*.sh pkg/*.sh"
bins="bin/* `find util -depth 1 -type f`"
diffs="pkg/*.diff"

nuos_ver_escd="$(echo $NUOS_VER | sed -e 's/\./\\./g')"

old_len=${#NUOS_VER}
new_len=${#new_ver}

if [ $old_len -gt $new_len ]; then
	add_spc=`printf %$(($old_len - $new_len))s ''`
fi
if [ $old_len -lt $new_len ]; then
	del_spc=`printf %$(($new_len - $old_len))s ''`
fi

sed -i '' -Ee "s/[[:<:]]nuOS $nuos_ver_escd[[:>:]]${del_spc-}/nuOS $new_ver${add_spc-}/" $readmes

sed -i '' -Ee "s/#([[:blank:]]*)nuOS $nuos_ver_escd[[:>:]]/#\\1nuOS $new_ver/" $libs $bins
sed -i '' -Ee "s/[[:<:]]NUOS_VER=$nuos_ver_escd[[:>:]]/NUOS_VER=$new_ver/" $bins
sed -i '' -Ee "s/[[:<:]]nuos_lib_ver=$nuos_ver_escd[[:>:]]/nuos_lib_ver=$new_ver/;s/\\\$NUOS_VER([[:blank:]]+)=([[:blank:]]+)$nuos_ver_escd[[:>:]]/\$NUOS_VER\\1=\\2$new_ver/" $libs

sed -i '' -Ee "s/#([[:blank:]]*current as of nuOS) $nuos_ver_escd[[:>:]]/#\\1 $new_ver/" $diffs

grep -n -r -E "$nuos_ver_escd\>" * && echo 'WARNING: old version string still present in codebase, see above' >&2

echo "Switched version label of nuOS $NUOS_VER codebase at $NUOS_CODE_ROOT to $new_ver."
