#!/bin/sh
set -e; set -u; set -C

# nuOS 0.0.11.4a0 - util/nush
#
# Copyright (c) 2008-2020 Chad Jacob Milios and Crop Circle Systems.
# All rights reserved.
#
# This Source Code Form is subject to the terms of the Simplified BSD License.
# If a copy of the Simplified BSD License was not distributed alongside this file, you can
# obtain one at https://www.freebsd.org/copyright/freebsd-license.html . This software
# project is not affiliated with the FreeBSD Project.
#
# Official updates and community support available at https://nuos.org .
# Professional services available at https://ccsys.com .

NUOS_VER=0.0.11.4a0
NUOS_CODE="$(dirname "$(realpath "$0")")/.."

. "$NUOS_CODE/lib/nu_system.sh"
. "$NUOS_CODE/lib/nu_common.sh"

while IFS= read _nush_interactive_line; do
	eval "$_nush_interactive_line"
done
